# -*- coding: utf-8 -*-
"""Multiple_Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10LrYJfJE3ecG3kYqQYDkAKgsxSj4QYZD

# Welcome to Colab!
"""

import pandas as pd

df = pd.read_csv("weight-height.csv")
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

import numpy as np
np.set_printoptions(precision = 2)
arr = np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)
print(arr[:20])

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 7))

plt.scatter(y_test, y_pred, color='blue', alpha=0.5, s=8, label='Predicted')
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    color='red',
    linewidth=1.5,
    label='Ideal Prediction (Actual = Predicted)'
)

plt.xlabel("Actual Weight")
plt.ylabel("Predicted Weight")
plt.title("Actual vs Predicted Weight")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.3)

plt.show()

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)